### PR TITLE
Fix of test for multiple arguments in info command

### PR DESCRIPTION
**Pull request by michal-josef-spacek**
Change in redis 7.0.0

Signed-off-by: Michal Josef Špaček <mspacek@redhat.com>

### CODE REVIEW

**Comment by gregoa** [comment]
I came here because of the test failures in Debian:  https://bugs.debian.org/1013523

Unfortunately the patch doesn't work as-is because 7.0.0 ist not a good match for redis 7.0.2 in Debian :)

`$r->info->{redis_version} ge '7.0.0'` works OTOH.

**Comment by michal-josef-spacek** [comment]
@gregoa I know. I prepared a new PR https://github.com/PerlRedis/perl-redis/pull/158

I don't like this kind of check (string comparison) still. Better is to have a major version in variable and checks against it.

**Comment by gregoa** [comment]
Thanks for the new PR!

(And yes, version checks are always a pain, and string comparisons are not elegant.)

**Comment by robbiebow** [comment]
Any ETA on when this will be pushed to PAUSE?

**Comment by dams** [comment]
pushd to CPAN as version 2.000

**Comment by robbiebow** [comment]
Oarsome!

**Pull request merged**
