### PR TITLE
Add SSL/TLS support.

### PR DESCRIPTION
**Pull request by huydhn**
All unit test have also been updated to connect to Redis over SSL/TLS when IO::Socket::SSL and stunnel are available.

### CODE REVIEW

**Comment by dams** [comment]
Would it be possible to have the tests run two times, first without ssl then with ssl enabled ?

**Comment by huydhn** [comment]
Well, the most straight forward fix that I can think of is to add a USE_SSL environment flag when running the unit tests.  So, `dzil test --release` runs the tests without SSL/TLS while `USE_SSL=1 dzil test --release` has SSL/TLS support.  Suggestions are welcome.

**Comment by dams** [comment]
That could work. I’ll try to get that working

**Comment by nunofernandes** [comment]
Hi guys.. any news on this? Thanks

**Comment by vrapolu0963** [comment]
> Hi guys.. any news on this? Thanks

Any update on this?

**Comment by dams** [comment]
I've merged support for ssl

**Pull request merged**
